// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = require("jquery");

  this.onUpdate = function(fileStatuses) {
    return $("#page").append($("<div id=\"last-updated-at\"></div>").text("Last updated at " + ((new Date).toLocaleTimeString())));
  };

}).call(this);
